import { ScanResult, GraphNode } from "./types";

/**
 * Generates an exhaustive, CISO-grade, executive attack-surface audit dossier
 * in GitHub Flavored Markdown format.
 */
export function generateAuditDossier(scanResult: ScanResult): string {
  const { summary, executive_summary, nodes, thoughts } = scanResult;
  const targetDomain = summary.target.toLowerCase();
  const scanDate = new Date().toUTCString();

  // Categorize nodes
  const vulnNodes = nodes.filter(
    (n) =>
      n.data.section === "VULNERABILITY" ||
      ((n.data.severity === "CRITICAL" ||
        n.data.severity === "HIGH" ||
        n.data.severity === "MEDIUM") &&
        n.data.category !== "VULN_STATUS_CLEAN")
  );

  const cleanNodes = nodes.filter((n) => n.data.category === "VULN_STATUS_CLEAN");

  const assetNodes = nodes.filter(
    (n) =>
      n.type === "rootNode" ||
      n.type === "subdomainNode" ||
      n.type === "assetNode" ||
      (n.data.section === "INFO" && !vulnNodes.includes(n))
  );

  const radarNodes = nodes.filter(
    (n) =>
      n.type === "externalNode" ||
      n.data.surface === "Threat Radar" ||
      n.data.section === "RESOURCE"
  );

  // Status indicator
  const riskStatus =
    summary.critical_risks > 0
      ? "CRITICAL PERIMETER EXPOSURE — BREACH RISK DETECTED"
      : summary.high_risks > 0
      ? "HIGH RISK PERIMETER — IMMEDIATE MITIGATION REQUIRED"
      : summary.medium_risks > 0
      ? "ELEVATED POSTURE DEFICIT — REMEDIATION RECOMMENDED"
      : "SECURE PERIMETER — PASSIVE SURFACE VERIFIED";

  let md = "";

  // ----------------------------------------------------
  // Title & Metadata
  // ----------------------------------------------------
  md += `# 🛡️ EXECUTIVE ATTACK SURFACE AUDIT DOSSIER\n\n`;
  md += `**Target Perimeter:** \`${targetDomain.toUpperCase()}\`  \n`;
  md += `**Generated By:** ReconFlow AI (Autonomous External Attack Surface Management Agent)  \n`;
  md += `**Audit Generation Date:** ${scanDate}  \n`;
  md += `**Security Posture Grade:** **${summary.security_grade}** (${summary.security_score}/100) — *${riskStatus}*  \n`;
  md += `**Autonomous Recon Engine:** SerpApi Multi-Engine Search Correlation (Google, Bing, DuckDuckGo, YouTube, Play)  \n`;
  md += `**SerpApi Search Credits Consumed:** ${summary.serpapi_credits_used} API Queries  \n\n`;
  md += `---\n\n`;

  // ----------------------------------------------------
  // 1. Executive Summary
  // ----------------------------------------------------
  md += `## 1. Executive Summary & Perimeter Health\n\n`;
  md += `${executive_summary}\n\n`;

  md += `### Perimeter Assessment Snapshot\n`;
  md += `- **Target Domain:** \`${targetDomain}\`\n`;
  md += `- **Posture Score:** **${summary.security_score}/100** (Grade: **${summary.security_grade}**)\n`;
  md += `- **Total Perimeter Entities Discovered:** **${summary.total_nodes}** nodes across subdomains, endpoints, and external threat intel\n`;
  md += `- **Active Exploitable Exposures:** **${summary.critical_risks + summary.high_risks}** (${summary.critical_risks} Critical, ${summary.high_risks} High)\n`;
  md += `- **Passive Intelligence Signals:** **${summary.low_risks}** subdomains & host assets mapped\n\n`;

  // ----------------------------------------------------
  // 2. Risk Distribution & Remediation SLAs
  // ----------------------------------------------------
  md += `## 2. Risk Distribution & Remediation SLAs\n\n`;
  md += `| Severity Tier | Discovered Count | Recommended Resolution SLA | Current Threat Status |\n`;
  md += `| :--- | :--- | :--- | :--- |\n`;
  md += `| 🔴 **CRITICAL** (CVSS 9.0 - 10.0) | **${summary.critical_risks}** | **< 24 Hours** | ${
    summary.critical_risks > 0 ? "🚨 **IMMEDIATE ACTION REQUIRED**" : "✅ Zero Detected"
  } |\n`;
  md += `| 🟠 **HIGH** (CVSS 7.0 - 8.9) | **${summary.high_risks}** | **< 72 Hours** | ${
    summary.high_risks > 0 ? "⚠️ **EXPEDITE REMEDIATION**" : "✅ Zero Detected"
  } |\n`;
  md += `| 🟡 **MEDIUM** (CVSS 4.0 - 6.9) | **${summary.medium_risks}** | **7 Business Days** | ${
    summary.medium_risks > 0 ? "📋 Scheduled Sprint Patch" : "✅ Zero Detected"
  } |\n`;
  md += `| 🔵 **LOW / HOST ASSETS** | **${summary.low_risks}** | **30 Calendar Days** | ℹ️ Hardening & Access Control |\n`;
  md += `| 🌐 **TOTAL GRAPH ENTITIES** | **${summary.total_nodes}** | **Continuous** | 📡 Attack Surface Monitored |\n\n`;

  // ----------------------------------------------------
  // 3. Deep-Dive Vulnerability Findings & Forensic Evidence
  // ----------------------------------------------------
  md += `## 3. Prioritized Vulnerability Deep-Dive & Forensic Evidence\n\n`;

  if (vulnNodes.length === 0) {
    md += `> ✅ **No active high or critical vulnerability findings unmasked.**\n`;
    md += `> The perimeter verified all automated search dork queries clean. Refer to Section 4 for host asset inventory.\n\n`;
  } else {
    vulnNodes.forEach((node, idx) => {
      const d = node.data;
      const cvss = d.cvss_score ? `CVSS ${d.cvss_score}` : "CVSS Pending";
      const owasp = d.owasp_tag || "OWASP Top 10";
      const cwe = d.cwe_id || "CWE-General";
      const targetUrl = d.metadata?.url || "N/A (Perimeter Root)";
      const dork = d.metadata?.dork_used || "N/A";
      const snippet = d.metadata?.snippet || "Evidence captured via live search engine snippet analysis.";

      md += `### [FINDING-${String(idx + 1).padStart(2, "0")}] ${d.label}\n\n`;
      md += `- **Severity Rating:** **${d.severity || "MEDIUM"}** (${cvss})\n`;
      md += `- **Standard Classification:** \`${owasp}\` | \`${cwe}\`\n`;
      md += `- **Attack Surface Sector:** \`${d.surface || "External Perimeter"}\`\n`;
      md += `- **Detection Engine:** SerpApi \`${d.engine || "google"}\` autonomous worker\n`;
      md += `- **Target Endpoint:** \`${targetUrl}\`\n\n`;

      md += `#### A. Forensic Proof & Exact SerpApi Dork Query\n`;
      if (dork && dork !== "N/A") {
        md += `\`\`\`bash\n# SerpApi Query Executed:\n${dork}\n\`\`\`\n`;
      }
      md += `**Search Engine Telemetry Proof Snippet:**\n`;
      md += `> "${snippet}"\n\n`;

      if (d.what_is_the_bug) {
        md += `#### B. Vulnerability Breakdown\n`;
        md += `${d.what_is_the_bug}\n\n`;
      }

      if (d.why_it_is_a_bug) {
        md += `#### C. Threat Mechanism & Business Impact\n`;
        md += `${d.why_it_is_a_bug}\n\n`;
      }

      if (d.attack_vector) {
        md += `#### D. Adversary Exploit Scenario\n`;
        md += `\`\`\`text\n${d.attack_vector}\n\`\`\`\n\n`;
      }

      if (d.triage_reason) {
        md += `#### E. Autonomous AI Triage Layer Verdict\n`;
        md += `*${d.triage_reason}*\n\n`;
      }

      md += `#### F. Defensive Remediation & Engineering Directives\n`;
      if (d.how_to_fix || d.remediation) {
        md += `**Primary Containment Action:**\n`;
        md += `${d.how_to_fix || d.remediation}\n\n`;
      }

      if (d.remediation_steps && d.remediation_steps.length > 0) {
        md += `**Step-by-Step Remediation Directives:**\n`;
        d.remediation_steps.forEach((step, sIdx) => {
          md += `${sIdx + 1}. \`${step}\`\n`;
        });
        md += `\n`;
      }

      md += `---\n\n`;
    });
  }

  // ----------------------------------------------------
  // 4. Discovered Perimeter Assets & Host Topology Inventory
  // ----------------------------------------------------
  md += `## 4. Discovered Perimeter Assets & Host Topology Inventory\n\n`;
  if (assetNodes.length === 0) {
    md += `*Primary target host evaluated: ${targetDomain}*\n\n`;
  } else {
    md += `| # | Asset / Hostname | Classification | Discovery Engine | Target URL / Surface |\n`;
    md += `| :--- | :--- | :--- | :--- | :--- |\n`;
    assetNodes.forEach((node, idx) => {
      const d = node.data;
      const url = d.metadata?.url || `https://${d.label}`;
      md += `| ${idx + 1} | **${d.label}** | \`${d.surface || "Subdomain Asset"}\` | \`${
        d.engine || "google"
      }\` | [${d.label}](${url}) |\n`;
    });
    md += `\n`;
  }

  // ----------------------------------------------------
  // 5. Threat Radar & External Intelligence (Phase 2 OSINT)
  // ----------------------------------------------------
  md += `## 5. Threat Radar & External Intelligence (Phase 2 OSINT)\n\n`;
  if (radarNodes.length === 0) {
    md += `*No external third-party repo leaks or public media PoCs identified for this perimeter.*\n\n`;
  } else {
    md += `ReconFlow AI cross-referenced secondary multi-engine intelligence vectors outside the core web server:\n\n`;
    radarNodes.forEach((node, idx) => {
      const d = node.data;
      const url = d.metadata?.url || "#";
      md += `### 5.${idx + 1} [${d.category || "INTEL"}] ${d.label}\n`;
      md += `- **Category Tag:** \`${d.surface || "External Intel"}\` | **Engine:** \`${d.engine || "SerpApi"}\`\n`;
      md += `- **Resource Link:** [${url}](${url})\n`;
      if (d.metadata?.snippet) {
        md += `- **Context Snippet:** *"${d.metadata.snippet}"*\n`;
      }
      if (d.what_is_the_bug || d.why_it_is_a_bug) {
        md += `- **Assessment:** ${d.what_is_the_bug || d.why_it_is_a_bug}\n`;
      }
      md += `\n`;
    });
  }

  // ----------------------------------------------------
  // 6. Actionable Defensive Playbooks (DevSecOps Patches)
  // ----------------------------------------------------
  md += `## 6. Actionable Defensive Playbooks (DevSecOps Patches)\n\n`;

  md += `### Playbook 6.1: Web Server Hardening (Nginx Configuration)\n`;
  md += `Deploy the following Nginx block to immediately drop traffic requesting sensitive dot-files, environment variables, backup dumps, and version control directories:\n\n`;
  md += `\`\`\`nginx
# Block access to hidden configuration files and environments
location ~ /\\.(env|git|svn|hg|bzr) {
    deny all;
    return 404;
}

# Block backup, sql dump, and temp files
location ~* \\.(bak|old|orig|backup|sql|tar|gz|zip|swp|temp)$ {
    deny all;
    return 404;
}

# Disable server directory listing
autoindex off;

# Enforce secure HTTP response headers
add_header X-Frame-Options "DENY" always;
add_header X-Content-Type-Options "nosniff" always;
add_header Referrer-Policy "strict-origin-when-cross-origin" always;
add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
\`\`\`\n\n`;

  md += `### Playbook 6.2: Compromised Secret Revocation & Git Scrubbing\n`;
  md += `If API keys, database credentials, or secret tokens were identified in public repositories or search results:\n\n`;
  md += `\`\`\`bash
# 1. Immediately revoke the exposed token in the cloud provider console
# 2. Rotate all dependant microservices with newly provisioned secrets
# 3. Purge sensitive credentials from git history before re-pushing:
git filter-repo --invert-paths --path-match .env
git push origin --force --all
\`\`\`\n\n`;

  md += `### Playbook 6.3: Amazon S3 & Cloud Storage IAM Policy Isolation\n`;
  md += `Ensure all cloud storage buckets linked to \`${targetDomain}\` disallow public anonymous listing:\n\n`;
  md += `\`\`\`json
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "BlockPublicListing",
      "Effect": "Deny",
      "Principal": "*",
      "Action": [
        "s3:ListBucket",
        "s3:ListBucketVersions"
      ],
      "Resource": "arn:aws:s3:::target-perimeter-*",
      "Condition": {
        "Bool": {
          "aws:PrincipalIsAWSService": "false"
        }
      }
    }
  ]
}
\`\`\`\n\n`;

  // ----------------------------------------------------
  // 7. CISO Compliance Assessment & Sign-Off Matrix
  // ----------------------------------------------------
  md += `## 7. CISO Compliance Assessment & Sign-Off Matrix\n\n`;
  md += `| Security Standard | Requirement / Control | Audit Result |\n`;
  md += `| :--- | :--- | :--- |\n`;
  md += `| **OWASP Top 10:2021** | A01: Broken Access Control | ${
    summary.critical_risks > 0 ? "❌ Non-Compliant (Active Exposure)" : "✅ Compliant"
  } |\n`;
  md += `| **OWASP Top 10:2021** | A05: Security Misconfiguration | ${
    summary.high_risks > 0 ? "⚠️ Remediation Required" : "✅ Compliant"
  } |\n`;
  md += `| **SOC 2 Type II** | CC6.6 External Perimeter Boundary Protection | ${
    summary.critical_risks === 0 ? "✅ Verified Defended" : "❌ Finding Logged"
  } |\n`;
  md += `| **ISO/IEC 27001:2022** | A.8.8 Management of Technical Vulnerabilities | 📋 Tracked via ReconFlow Dossier |\n\n`;

  md += `### Executive Attestation & Sign-Off\n\n`;
  md += `| Role | Signature / Title | Date |\n`;
  md += `| :--- | :--- | :--- |\n`;
  md += `| **Lead EASM Auditor:** | ReconFlow AI Autonomous Agent v2.4 | ${scanDate} |\n`;
  md += `| **Target Security Contact:** | Corporate Security Officer (\`@${targetDomain}\`) | ____________________ |\n`;
  md += `| **Remediation Sign-Off:** | Chief Information Security Officer (CISO) | ____________________ |\n\n`;

  md += `> *Confidential Security Telemetry: This dossier contains proprietary attack surface intelligence generated exclusively for authorized corporate personnel of \`${targetDomain}\`. Unauthorized distribution is strictly prohibited.*\n`;

  return md;
}
